name: Trigger auto deployment for smwhatsappbot-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/smwhatsappbot-ca-AutoDeployTrigger-1bc97b93-bdf7-4477-ba05-153fec5c8506.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SMWHATSAPPBOTCA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SMWHATSAPPBOTCA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SMWHATSAPPBOTCA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.SMWHATSAPPBOTCA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SMWHATSAPPBOTCA_REGISTRY_PASSWORD }}
          containerAppName: smwhatsappbot-ca
          resourceGroup: sm-function-rg
          imageToBuild: matandreoli/smwhatsappbot-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


